#!/bin/bash
# HealthPay: Technical Appendix & Revenue Projection for VC Due Diligence

source ~/HealthPay/core/treasury/.stellar_keys 2>/dev/null
OUTPUT_FILE=~/HealthPay/HealthPay_Technical_Appendix.txt

{
echo "=========================================================="
echo "      HEALTHPAY TECHNICAL APPENDIX: PROTOTYPE V1.0        "
echo "=========================================================="
echo "DATE: $(date '+%Y-%m-%d')"
echo "NETWORK: Stellar Testnet"
echo "STATUS: Live / Functional Prototype"
echo "----------------------------------------------------------"
echo ""
echo "1. ASSET SPECIFICATIONS (HealthCoin)"
echo "------------------------------------"
echo "Asset Code:      HLTC"
echo "Supply Policy:   Controlled Minting (Treasury Managed)"
echo "Asset Type:      Purpose-Bound Health Liquidity"
echo ""
echo "2. SAAS REVENUE TIERS (2026 PRICING MODEL)"
echo "------------------------------------"
echo "| Company Size | Tier Name   | Monthly Fee (ZAR) |"
echo "|--------------|-------------|-------------------|"
echo "| 1-10 Staff   | Foundation  | R 499             |"
echo "| 11-25 Staff  | Growth      | R 999             |"
echo "| 26-50 Staff  | Expansion   | R 1799            |"
echo "Note: Pricing scales per company size beyond 10 employees."
echo ""
echo "3. PROJECTED YIELD STREAMS"
echo "------------------------------------"
echo "Primary:   Fixed SaaS Subscription Fee"
echo "Secondary: 1.5% Merchant Discount Rate (MDR) on HLTC Spend"
echo "Status:    Yield is provider-funded; 0% cost to worker."
echo ""
echo "4. PORTABILITY ARCHITECTURE"
echo "------------------------------------"
echo "Philosophy: Portable health equity for the worker."
echo "Logic: Employees retain wallet balances post-employment."
echo "Network: Stellar Blockchain (Finality ~5 seconds)."
echo ""
echo "5. REGULATORY ALIGNMENT"
echo "------------------------------------"
echo "Framework: SARB Fintech Sandbox Compatibility"
echo "Currency: Native HealthCoin (HLTC) - Purpose-Bound"
echo "----------------------------------------------------------"
echo "CONFIDENTIAL: FOR VENTURE STUDIO / VC REVIEW ONLY"
echo "=========================================================="
} > "$OUTPUT_FILE"

echo "Updated Technical Appendix with Revenue Projections: $OUTPUT_FILE"
