#!/bin/bash
# Ħ HEALTHPAY: Pitch & Value Proposition 2026

echo "=================================================="
echo "          Ħ HEALTHPAY: INVESTOR PREVIEW           "
echo "=================================================="
echo "THE PROBLEM:"
echo " - SMEs find healthcare administration too costly."
echo " - Legacy banking delays benefit payments by days."
echo ""
echo "THE SOLUTION:"
echo " - A Stellar-based disbursement engine."
echo " - Native Asset: HealthCoin (Ħ)."
echo " - Instant, transparent, and low-cost."
echo ""
echo "THE MODEL (SME FOCUS):"
echo " - 1-10 Employees: R499/month (Base Tier)."
echo " - 11+ Employees: Scalable enterprise pricing."
echo " - SaaS Fee: R150 per employee/month."
echo ""
echo "TRACTION (LIVE DEMO READY):"
echo " [✔] 1,000,000 Ħ Treasury Minted."
echo " [✔] SME Onboarding Logic Operational."
echo " [✔] Verified Audit Trail on Stellar Testnet."
echo "=================================================="
